routes/web.php
<?php

/**
 * @var \Illuminate\Routing\Router $router
 */
$router->auth();
$router->get('auth/{provider}/sign', 'Auth\SocialSignController@redirectToProvider')->name('auth.social_sign');
$router->get('auth/{provider}/callback', 'Auth\SocialSignController@handleProviderCallback')->name('auth.social_sign_callback');

$router->get('/', 'HomeController@index')->name('index');
$router->get('home', 'HomeController@index')->name('home');
$router->get('countries/regions', 'RegionController@getRegionsByCountry')->name('countries.get_regions');
$router->get('regions/cities', 'CityController@getRegionsByCountry')->name('regions.get_cities');
$router->get('cities', 'CityController@index')->name('cities.index');
$router->get('cities/{id}', 'CityController@show')->name('city.show');
$router->get('breeds', 'BreedController@index')->name('breeds.index');

$router->get('pets', 'PostController@index')->name('posts.index');
$router->get('pets/{slug}', 'PostController@show')->name('posts.show');


//$router->get('shop', 'PostController@productsIndex')->name('posts.index');
//$router->get('shop/{category}/{slug}', 'PostController@showProduct')->name('posts.show');

$router->post('pets/send-message', 'PostController@submitMessage')->name('posts.send_message');

$router->get('organizations', 'OrganizationController@index')->name('organizations.index');
$router->get('organizations/{slug}', 'OrganizationController@show')->name('organizations.show');

Route::get('sitemap', function () {
    return redirect()->route('sitemap_xml', 302);
});
Route::get('sitemap.xml', 'HomeController@sitemap')->name('sitemap_xml');


$router->group(['middleware' => 'auth', 'prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Profile'], function () use ($router) {
    $router->get('/', 'IndexController@index')->name('index');
    $router->put('update', 'IndexController@update')->name('update');
    $router->get('favourites', 'FavouritesController@index')->name('favourites.index');
    $router->post('posts/add-to-favourites', 'PostController@addToFavourites')->name('posts.add_to_favourites');
    $router->delete('posts/remove-from-favourites', 'PostController@removeFromFavourites')->name('posts.remove_from_favourites');
    $router->post('posts/delete-image', 'PostController@deleteImage')->name('posts.delete_image');
    $router->post('posts/photos/mark-as-main', 'PostController@markPhotoAsMain')->name('posts.photos.mark_as_main');
    $router->put('posts/change-home-status/{id}', 'PostController@changeHomeStatus')->name('posts.change_home_status');
    $router->resource('posts', 'PostController');

    $router->post('organizations/delete-image', 'OrganizationController@deleteImage')->name('organizations.delete_image');
    $router->resource('organizations', 'OrganizationController');
});
$router->group(['middleware' => 'can:admin', 'prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function () use ($router) {
    $router->get('/', 'IndexController@index')->name('index');
    $router->get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

    $router->get('grabber', 'IndexController@grabber')->name('grabber.index');
    $router->post('grabber', 'IndexController@grabberRun')->name('grabber.run');

    $router->get('robots', 'IndexController@robots')->name('robots.index');
    $router->post('robots', 'IndexController@storeRobots')->name('robots.store');

    $router->post('categories/delete-img', 'CategoriesController@deleteImg')->name('categories.delete_img');
    $router->resource('categories', 'CategoriesController');
    $router->resource('users', 'UsersController');
    $router->resource('settings', 'SettingsController');
    $router->resource('pages', 'PageController');
    $router->resource('posts', 'PostController');
    $router->resource('breeds', 'BreedController');
    $router->resource('breed-types', 'BreedTypeController');
    $router->resource('post-types', 'PostTypeController');
    $router->resource('colors', 'ColorController');
    $router->resource('countries', 'CountryController');
    $router->resource('regions', 'RegionController');
    $router->resource('cities', 'CityController');
    $router->resource('organizations', 'OrganizationController');
    $router->resource('organization-types', 'OrganizationTypeController');

});

$router->get('{slug}', 'HomeController@showStaticPage')->name('page.show');

app/Models/Color.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\Color
 *
 * @property int $id
 * @property string $title
 * @property \Carbon\Carbon|null $created_at
 * @property \Carbon\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Color whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Color whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Color whereTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Color whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class Color extends Model
{
    protected $fillable = [
        'title'
    ];
}

app/Http/Controllers/Admin/ColorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Color;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ColorController extends Controller
{
    private $model;

    public function __construct(Color $model)
    {
        $this->model = $model;
    }

    public function index()
    {
        $this->viewData['colors'] = $this->model->orderBy('title')->get();

        return view('admin.colors.index', $this->viewData);
    }

    public function create()
    {
        $this->viewData['color'] = $this->model;

        return view('admin.colors.create_edit', $this->viewData);
    }

    public function store(Request $request)
    {
        $this->validate($request, ['title' => 'unique:colors,title']);
        $data = $request->all();
        $data['slug'] = str_slug($data['title']);

        $model = $this->model->fill($data);
        if ($model->save()) {
            return redirect()->route('admin.colors.index')->with('success', __('flash.created'));
        } else {
            return back()->with('error', __('flash.error'));
        }
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $this->viewData['color'] = $this->model->findOrFail($id);

        return view('admin.colors.create_edit', $this->viewData);
    }

    public function update(Request $request, $id)
    {
        $data = $request->all();
        $data['slug'] = str_slug($data['title']);
        $breed = $this->model->findOrFail($id);
        $model = $breed->fill($data);
        if ($model->save()) {
            return redirect()->route('admin.colors.index')->with('success', __('flash.updated'));
        } else {
            return back()->with('error', __('flash.error'));
        }
    }

    public function destroy($id)
    {
        $breed = $this->model->findOrFail($id);
        if ($breed->delete($id)) {
            return back()->with('success', __('flash.deleted'));
        } else {
            return back()->with('error', __('flash.error'));
        }
    }
}

resources/views/admin/colors/create_edit.blade.php
@extends('admin.layouts.common')
@section('title') {{ isset($color->id) ? 'Редактирование расцветки - ' . $color->title : 'Содание расцветки' }} @endsection
@section('css')
    @parent
@stop

@section('scripts')
    @parent
@stop
@push('breadcrumbs')
    <li>
        <a href="{{ route('admin.colors.index') }}">Расцветки</a>
    </li>
@endpush
@push('active_breadcrumb')
    {{ $color->title ? $color->title : 'Содание расцветки'}}
@endpush
@section('content')
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h3 class="panel-title">{{ isset($color->id) ? 'Редактирование расцветки - ' . $color->title : 'Содание расцветки' }}</h3>
        </div>
        <div class="panel-body">
            <div class="tabbable">
                @if(empty($color->id))
                    <form action="{{ route('admin.colors.store') }}" method="post" class="form-horizontal" role="form" enctype="multipart/form-data" id="form">
                @else
                    <form action="{{ route('admin.colors.update', ['id' => $color->id]) }}" method="post" class="form-horizontal" role="form" enctype="multipart/form-data" id="form">
                    {{ method_field('PUT') }}
                @endif
                    {{ csrf_field() }}
                    <fieldset class="content-group">
                        <div class="form-group row @if($errors->has('title'))has-error has-feedback @endif">
                            <label class="control-label col-md-2 text-semibold">Название</label>
                            <div class="col-md-10">
                                <input type="text" name="title" class="form-control" value="{{ old('title', $color->title) }}">
                                @if($errors->has('title'))
                                    <div class="form-control-feedback">
                                        <i class="icon-cancel-circle2"></i>
                                    </div>
                                    <span class="help-block">{{$errors->first('title')}}</span>
                                @endif
                            </div>
                        </div>
                    </fieldset>

                    <ul class="fab-menu fab-menu-fixed fab-menu-bottom-left">
                        <li style="display: inline">
                            <a class="fab-menu-btn btn btn-default btn-float btn-rounded btn-icon" href="{{ route('admin.colors.index') }}">
                                <i class="fab-icon-open icon-arrow-left8"></i>
                            </a>
                        </li>
                        <li style="display: inline">
                            <a class="fab-menu-btn btn bg-primary-400 btn-float btn-rounded btn-icon" onclick="$('#form').submit();">
                                <i class="fab-icon-open icon-floppy-disk"></i>
                            </a>
                        </li>
                    </ul>

            </form>
            </div>
        </div>
    </div>
@stop

resources/views/admin/colors/index.blade.php
@extends('admin.layouts.common')

@section('title', 'Расцветки животных')
@section('content')
    <div class="row">
        @push('active_breadcrumb')
            Список расцветок
        @endpush
        <div class="col-xs-12">
            <div class="panel panel-flat">
                <div class="panel-heading">
                    <h6 class="panel-title">Список расцветок</h6>
                    <div class="row">
                        <a href="{{ route('admin.colors.create') }}" class="pull-right btn btn-success">Добавить расцветку</a>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table text-nowrap">
                            <thead>
                            <tr class="active">
                                <th class="text-center">ID</th>
                                <th>Название</th>
                                <th>Создано</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($colors as $color)
                                <tr>
                                    <td class="text-center">
                                        {{ $color->id }}
                                    </td>
                                    <td>
                                        <b>{{ $color->title }}</b>
                                    </td>
                                    <td>
                                        <b>{{ $color->created_at->format('Y.m.d H:i') }}</b>
                                    </td>
                                    <td class="text-center">
                                        <div class="btn-group">
                                            <a href="{{ route('admin.colors.edit', ['id' => $color->id]) }}" class="btn bg-slate btn-xs"><i class="fa fa-pencil"></i></a>
                                            <form action="{{ route('admin.colors.destroy', ['id' => $color->id]) }}" method="post">
                                                {{ csrf_field() }}{{  method_field('DELETE') }}
                                                <button onclick="if(!confirm('Удалить?')){return false;}" class="btn btn-danger btn-xs"><i class="fa fa-trash"></i></button>
                                            </form>
                                        </div>

                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection