routes/web.php
<?php

/**
 * @var \Illuminate\Routing\Router $router
 */
$router->auth();
$router->get('auth/{provider}/sign', 'Auth\SocialSignController@redirectToProvider')->name('auth.social_sign');
$router->get('auth/{provider}/callback', 'Auth\SocialSignController@handleProviderCallback')->name('auth.social_sign_callback');

$router->get('/', 'HomeController@index')->name('index');
$router->get('home', 'HomeController@index')->name('home');
$router->get('countries/regions', 'RegionController@getRegionsByCountry')->name('countries.get_regions');
$router->get('regions/cities', 'CityController@getRegionsByCountry')->name('regions.get_cities');
$router->get('cities', 'CityController@index')->name('cities.index');
$router->get('cities/{id}', 'CityController@show')->name('city.show');
$router->get('breeds', 'BreedController@index')->name('breeds.index');

$router->get('pets', 'PostController@index')->name('posts.index');
$router->get('pets/{slug}', 'PostController@show')->name('posts.show');


//$router->get('shop', 'PostController@productsIndex')->name('posts.index');
//$router->get('shop/{category}/{slug}', 'PostController@showProduct')->name('posts.show');

$router->post('pets/send-message', 'PostController@submitMessage')->name('posts.send_message');

$router->get('organizations', 'OrganizationController@index')->name('organizations.index');
$router->get('organizations/{slug}', 'OrganizationController@show')->name('organizations.show');

Route::get('sitemap', function () {
    return redirect()->route('sitemap_xml', 302);
});
Route::get('sitemap.xml', 'HomeController@sitemap')->name('sitemap_xml');


$router->group(['middleware' => 'auth', 'prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Profile'], function () use ($router) {
    $router->get('/', 'IndexController@index')->name('index');
    $router->put('update', 'IndexController@update')->name('update');
    $router->get('favourites', 'FavouritesController@index')->name('favourites.index');
    $router->post('posts/add-to-favourites', 'PostController@addToFavourites')->name('posts.add_to_favourites');
    $router->delete('posts/remove-from-favourites', 'PostController@removeFromFavourites')->name('posts.remove_from_favourites');
    $router->post('posts/delete-image', 'PostController@deleteImage')->name('posts.delete_image');
    $router->post('posts/photos/mark-as-main', 'PostController@markPhotoAsMain')->name('posts.photos.mark_as_main');
    $router->put('posts/change-home-status/{id}', 'PostController@changeHomeStatus')->name('posts.change_home_status');
    $router->resource('posts', 'PostController');

    $router->post('organizations/delete-image', 'OrganizationController@deleteImage')->name('organizations.delete_image');
    $router->resource('organizations', 'OrganizationController');
});
$router->group(['middleware' => 'can:admin', 'prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function () use ($router) {
    $router->get('/', 'IndexController@index')->name('index');
    $router->get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

    $router->get('grabber', 'IndexController@grabber')->name('grabber.index');
    $router->post('grabber', 'IndexController@grabberRun')->name('grabber.run');

    $router->get('robots', 'IndexController@robots')->name('robots.index');
    $router->post('robots', 'IndexController@storeRobots')->name('robots.store');

    $router->post('categories/delete-img', 'CategoriesController@deleteImg')->name('categories.delete_img');
    $router->resource('categories', 'CategoriesController');
    $router->resource('users', 'UsersController');
    $router->resource('settings', 'SettingsController');
    $router->resource('pages', 'PageController');
    $router->resource('posts', 'PostController');
    $router->resource('breeds', 'BreedController');
    $router->resource('breed-types', 'BreedTypeController');
    $router->resource('post-types', 'PostTypeController');
    $router->resource('colors', 'ColorController');
    $router->resource('countries', 'CountryController');
    $router->resource('regions', 'RegionController');
    $router->resource('cities', 'CityController');
    $router->resource('organizations', 'OrganizationController');
    $router->resource('organization-types', 'OrganizationTypeController');

});

$router->get('{slug}', 'HomeController@showStaticPage')->name('page.show');

app/Models/Breed.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\Breed
 *
 * @property int $id
 * @property int|null $breed_type_id
 * @property string $title
 * @property string|null $slug
 * @property int|null $order
 * @property \Carbon\Carbon|null $created_at
 * @property \Carbon\Carbon|null $updated_at
 * @property-read \App\Models\BreedType|null $breedType
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Breed whereBreedTypeId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Breed whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Breed whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Breed whereSlug($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Breed whereOrder($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Breed whereTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Breed whereUpdatedAt($value)
 * @mixin \Eloquent
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Post[] $posts
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Breed ordered()
 */
class Breed extends Model
{
    protected $fillable = [
        'breed_type_id',
        'title',
        'slug',
        'order',
    ];

    public function breedType()
    {
        return $this->belongsTo(BreedType::class);
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    public function scopeOrdered($query)
    {
        return $query->orderby('order', 'desc')->orderBy('title');
    }
}

app/Models/BreedType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\BreedType
 *
 * @property int $id
 * @property string $title
 * @property string|null $slug
 * @property string|null $image
 * @property int|null $order
 * @property \Carbon\Carbon|null $created_at
 * @property \Carbon\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\BreedType whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\BreedType whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\BreedType whereSlug($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\BreedType whereImage($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\BreedType whereOrder($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\BreedType whereTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\BreedType whereUpdatedAt($value)
 * @mixin \Eloquent
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Breed[] $breeds
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\BreedType ordered()
 */
class BreedType extends Model
{
    protected $fillable = [
        'title',
        'slug',
        'image',
        'order',
    ];

    public function breeds()
    {
        return $this->hasMany(Breed::class, 'breed_type_id', 'id');
    }

    public function scopeOrdered($query)
    {
        return $query->orderby('order', 'desc')->orderBy('title');
    }
}

app/Http/Controllers/Admin/BreedController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Breed;
use App\Models\BreedType;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BreedController extends Controller
{
    private $breed;
    private $breedType;

    public function __construct(Breed $breed, BreedType $breedType)
    {
        $this->breed = $breed;
        $this->breedType = $breedType;
    }

    public function index()
    {
        $this->viewData['breedTypes'] = $this->breedType->with('breeds')->get();

        return view('admin.breeds.index', $this->viewData);
    }

    public function create()
    {
        $this->viewData['breedTypes'] = $this->breedType->all();
        $this->viewData['breed'] = $this->breed;

        return view('admin.breeds.create_edit', $this->viewData);
    }

    public function store(Request $request)
    {
        $data = $request->all();
        $data['slug'] = str_slug($data['title']);

        $model = $this->breed->fill($data);
        if ($model->save()) {
            return redirect()->route('admin.breeds.index')->with('success', __('flash.created'));
        } else {
            return back()->with('error', __('flash.error'));
        }
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $this->viewData['breedTypes'] = $this->breedType->all();
        $this->viewData['breed'] = $this->breed->findOrFail($id);

        return view('admin.breeds.create_edit', $this->viewData);
    }

    public function update(Request $request, $id)
    {
        $data = $request->all();
        $data['slug'] = str_slug($data['title']);
        $breed = $this->breed->findOrFail($id);
        $model = $breed->fill($data);
        if ($model->save()) {
            return redirect()->route('admin.breeds.index')->with('success', __('flash.updated'));
        } else {
            return back()->with('error', __('flash.error'));
        }
    }

    public function destroy($id)
    {
        $breed = $this->breed->findOrFail($id);
        if ($breed->delete($id)) {
            return back()->with('success', __('flash.deleted'));
        } else {
            return back()->with('error', __('flash.error'));
        }
    }
}

app/Http/Controllers/BreedController.php
<?php

namespace App\Http\Controllers;

use App\Models\Breed;
use Illuminate\Http\Request;

class BreedController extends Controller
{
    /**
     * @var Breed
     */
    private $model;

    public function __construct(Breed $model)
    {
        $this->model = $model;
    }

    public function index(Request $request)
    {
        $region_id = $request->get('breed_type_id', null);
        $this->viewData['status'] = 'ok';
        $this->viewData['data']['breeds'] = $this->model->where('breed_type_id', $region_id)->ordered()->get();

        return response()->json($this->viewData);
    }
}

resources/views/admin/breeds/create_edit.blade.php
@extends('admin.layouts.common')
@section('title') {{ isset($breed->id) ? 'Редактирование породы' : 'Содание породы' }} @endsection
@section('css')
    @parent
@stop

@section('scripts')
    @parent
@stop
@push('breadcrumbs')
    <li>
        <a href="{{ route('admin.breeds.index') }}">Породы</a>
    </li>
@endpush
@push('active_breadcrumb')
    {{ $breed->title ? $breed->title : 'Содание породы'}}
@endpush
@section('content')
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h3 class="panel-title">{{ isset($breed->id) ? 'Редактирование породы' : 'Содание породы' }}</h3>
        </div>
        <div class="panel-body">
            <div class="tabbable">
                @if(empty($breed->id))
                    <form action="{{ route('admin.breeds.store') }}" method="post" class="form-horizontal" role="form" enctype="multipart/form-data" id="form">
                @else
                    <form action="{{ route('admin.breeds.update', ['id' => $breed->id]) }}" method="post" class="form-horizontal" role="form" enctype="multipart/form-data" id="form">
                    {{ method_field('PUT') }}
                @endif
                    {{ csrf_field() }}
                    <fieldset class="content-group">
                        <legend class="text-bold">Main info</legend>
                        <div class="form-group row @if($errors->has('breed_type_id'))has-error has-feedback @endif">
                            <label class="control-label col-md-2 text-semibold">Вид</label>
                            <div class="col-md-10">
                                <select name="breed_type_id" class="form-control">
                                    @foreach($breedTypes as $breedType)
                                        <option value="{{ $breedType->id }}" {{old('breed_type_id', $breed->breed_type_id) == $breedType->id ? 'selected' : '' }}>{{ $breedType->title }}</option>
                                    @endforeach
                                </select>
                                @if($errors->has('breed_type_id'))
                                    <div class="form-control-feedback">
                                        <i class="icon-cancel-circle2"></i>
                                    </div>
                                    <span class="help-block">{{$errors->first('breed_type_id')}}</span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row @if($errors->has('order'))has-error has-feedback @endif">
                            <label class="control-label col-md-2 text-semibold">Порядок сортировки (Чем больше - тем выше в списке)</label>
                            <div class="col-md-10">
                                <input type="number" name="order" class="form-control" value="{{ old('order', $breed->order) }}">
                                @if($errors->has('order'))
                                    <div class="form-control-feedback">
                                        <i class="icon-cancel-circle2"></i>
                                    </div>
                                    <span class="help-block">{{$errors->first('order')}}</span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row @if($errors->has('title'))has-error has-feedback @endif">
                            <label class="control-label col-md-2 text-semibold">Название</label>
                            <div class="col-md-10">
                                <input type="text" name="title" class="form-control" value="{{ old('title', $breed->title) }}">
                                @if($errors->has('title'))
                                    <div class="form-control-feedback">
                                        <i class="icon-cancel-circle2"></i>
                                    </div>
                                    <span class="help-block">{{$errors->first('title')}}</span>
                                @endif
                            </div>
                        </div>
                    </fieldset>

                    <ul class="fab-menu fab-menu-fixed fab-menu-bottom-left">
                        <li style="display: inline">
                            <a class="fab-menu-btn btn btn-default btn-float btn-rounded btn-icon" href="{{ route('admin.breeds.index') }}">
                                <i class="fab-icon-open icon-arrow-left8"></i>
                            </a>
                        </li>
                        <li style="display: inline">
                            <a class="fab-menu-btn btn bg-primary-400 btn-float btn-rounded btn-icon" onclick="$('#form').submit();">
                                <i class="fab-icon-open icon-floppy-disk"></i>
                            </a>
                        </li>
                    </ul>

            </form>
            </div>
        </div>
    </div>
@stop

resources/views/admin/breeds/index.blade.php
@extends('admin.layouts.common')

@section('title', 'Породы')
@section('content')
    <div class="row">
        @push('active_breadcrumb')
            Список пород
        @endpush
        <div class="col-xs-12">
            <div class="panel panel-flat">
                <div class="panel-heading">
                    <h6 class="panel-title">Список пород</h6>
                    <a href="{{ route('admin.breeds.create') }}" class="pull-right btn btn-success">Добавить породу</a>
                </div>
                <div class="panel-body">
                    <!-- TAB NAVIGATION -->
                    <ul class="nav nav-tabs" role="tablist">
                        @foreach($breedTypes as $breedType)
                            <li class="{{ $loop->index == 0 ? 'active' : '' }}">
                                <a href="#tab{{ $breedType->id }}" role="tab" data-toggle="tab">{{ $breedType->title }} ({{ $breedType->breeds()->count() }})</a>
                            </li>
                        @endforeach
                    </ul>
                    <!-- TAB CONTENT -->
                    <div class="tab-content">
                        @foreach($breedTypes as $breedType)
                            <div class="{{ $loop->index == 0 ? 'active' : '' }} tab-pane fade in" id="tab{{ $breedType->id }}">
                                <div class="table-responsive">
                                    <table class="table text-nowrap">
                                        <thead>
                                        <tr class="active">
                                            <th class="text-center">ID</th>
                                            <th>Название</th>
                                            <th>К-тво объяв</th>
                                            <th>Создано</th>
                                            <th></th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($breedType->breeds as $breed)
                                            <tr>
                                                <td class="text-center">
                                                    {{ $breed->id }}
                                                </td>
                                                <td>
                                                    <b>{{ $breed->title }}</b>
                                                </td>
                                                <td>
                                                    <b><span class="label label-info">{{ $breed->posts()->count() }}</span></b>
                                                </td>
                                                <td>
                                                    <b>{{ $breed->created_at->format('Y.m.d H:i') }}</b>
                                                </td>
                                                <td class="text-center">
                                                    <div class="btn-group">
                                                        <a href="{{ route('admin.breeds.edit', ['id' => $breed->id]) }}" class="btn bg-slate btn-xs"><i class="fa fa-pencil"></i></a>
                                                        <form action="{{ route('admin.breeds.destroy', ['id' => $breed->id]) }}" method="post">
                                                            {{ csrf_field() }}{{  method_field('DELETE') }}
                                                            <button onclick="if(!confirm('Удалить?')){return false;}" class="btn btn-danger btn-xs"><i class="fa fa-trash"></i></button>
                                                        </form>
                                                    </div>

                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        @endforeach

                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection