routes/web.php
<?php

/**
 * @var \Illuminate\Routing\Router $router
 */
$router->auth();
$router->get('auth/{provider}/sign', 'Auth\SocialSignController@redirectToProvider')->name('auth.social_sign');
$router->get('auth/{provider}/callback', 'Auth\SocialSignController@handleProviderCallback')->name('auth.social_sign_callback');

$router->get('/', 'HomeController@index')->name('index');
$router->get('home', 'HomeController@index')->name('home');
$router->get('countries/regions', 'RegionController@getRegionsByCountry')->name('countries.get_regions');
$router->get('regions/cities', 'CityController@getRegionsByCountry')->name('regions.get_cities');
$router->get('cities', 'CityController@index')->name('cities.index');
$router->get('cities/{id}', 'CityController@show')->name('city.show');
$router->get('breeds', 'BreedController@index')->name('breeds.index');

$router->get('pets', 'PostController@index')->name('posts.index');
$router->get('pets/{slug}', 'PostController@show')->name('posts.show');


//$router->get('shop', 'PostController@productsIndex')->name('posts.index');
//$router->get('shop/{category}/{slug}', 'PostController@showProduct')->name('posts.show');

$router->post('pets/send-message', 'PostController@submitMessage')->name('posts.send_message');

$router->get('organizations', 'OrganizationController@index')->name('organizations.index');
$router->get('organizations/{slug}', 'OrganizationController@show')->name('organizations.show');

Route::get('sitemap', function () {
    return redirect()->route('sitemap_xml', 302);
});
Route::get('sitemap.xml', 'HomeController@sitemap')->name('sitemap_xml');


$router->group(['middleware' => 'auth', 'prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Profile'], function () use ($router) {
    $router->get('/', 'IndexController@index')->name('index');
    $router->put('update', 'IndexController@update')->name('update');
    $router->get('favourites', 'FavouritesController@index')->name('favourites.index');
    $router->post('posts/add-to-favourites', 'PostController@addToFavourites')->name('posts.add_to_favourites');
    $router->delete('posts/remove-from-favourites', 'PostController@removeFromFavourites')->name('posts.remove_from_favourites');
    $router->post('posts/delete-image', 'PostController@deleteImage')->name('posts.delete_image');
    $router->post('posts/photos/mark-as-main', 'PostController@markPhotoAsMain')->name('posts.photos.mark_as_main');
    $router->put('posts/change-home-status/{id}', 'PostController@changeHomeStatus')->name('posts.change_home_status');
    $router->resource('posts', 'PostController');

    $router->post('organizations/delete-image', 'OrganizationController@deleteImage')->name('organizations.delete_image');
    $router->resource('organizations', 'OrganizationController');
});
$router->group(['middleware' => 'can:admin', 'prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function () use ($router) {
    $router->get('/', 'IndexController@index')->name('index');
    $router->get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

    $router->get('grabber', 'IndexController@grabber')->name('grabber.index');
    $router->post('grabber', 'IndexController@grabberRun')->name('grabber.run');

    $router->get('robots', 'IndexController@robots')->name('robots.index');
    $router->post('robots', 'IndexController@storeRobots')->name('robots.store');

    $router->post('categories/delete-img', 'CategoriesController@deleteImg')->name('categories.delete_img');
    $router->resource('categories', 'CategoriesController');
    $router->resource('users', 'UsersController');
    $router->resource('settings', 'SettingsController');
    $router->resource('pages', 'PageController');
    $router->resource('posts', 'PostController');
    $router->resource('breeds', 'BreedController');
    $router->resource('breed-types', 'BreedTypeController');
    $router->resource('post-types', 'PostTypeController');
    $router->resource('colors', 'ColorController');
    $router->resource('countries', 'CountryController');
    $router->resource('regions', 'RegionController');
    $router->resource('cities', 'CityController');
    $router->resource('organizations', 'OrganizationController');
    $router->resource('organization-types', 'OrganizationTypeController');

});

$router->get('{slug}', 'HomeController@showStaticPage')->name('page.show');

app/Models/Category.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\Category
 *
 * @property int $id
 * @property int|null $parent_id
 * @property string $slug
 * @property string $title
 * @property string|null $image
 * @property string|null $description
 * @property string|null $seo_title
 * @property string|null $seo_h1
 * @property string|null $seo_description
 * @property string|null $seo_keywords
 * @property int $active
 * @property int $show_on_main
 * @property int $show_in_menu
 * @property \Carbon\Carbon|null $created_at
 * @property \Carbon\Carbon|null $updated_at
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Category[] $child
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Favourite[] $favourites
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Category active()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Category main()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Category menu()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Category whereActive($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Category whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Category whereDescription($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Category whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Category whereImage($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Category whereParentId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Category whereSeoDescription($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Category whereSeoH1($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Category whereSeoKeywords($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Category whereSeoTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Category whereShowInMenu($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Category whereShowOnMain($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Category whereSlug($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Category whereTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Category whereUpdatedAt($value)
 * @mixin \Eloquent
 * @property int $is_for_sale
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Category forSale()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Category whereIsForSale($value)
 */
class Category extends Model
{
    protected $fillable = [
        'parent_id',
        'slug',
        'title',
        'image',
        'description',
        'seo_title',
        'seo_h1',
        'seo_description',
        'seo_keywords',
        'active',
        'show_on_main',
        'show_in_menu',
        'big_caption',
        'is_for_sale',
    ];

    public function child()
    {
        return $this->hasMany(Category::class, 'parent_id', 'id');
    }

    public function favourites()
    {
        return $this->morphMany(Favourite::class, 'favourited');
    }

    public function scopeActive($query)
    {
        return $query->where('active', true);
    }

    public function scopeForSale($query)
    {
        return $query->where('is_for_sale', true);
    }

    public function scopeMain($query)
    {
        return $query->where('show_on_main', true);
    }

    public function scopeMenu($query)
    {
        return $query->where('show_in_menu', true);
    }

    public function getCreatedAtAttribute($value)
    {
        return Carbon::parse($value)->format('Y-m-d');
    }
}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\Categories\DeleteCategoryRequest;
use App\Http\Requests\Categories\StoreCategoryRequest;
use App\Http\Requests\Categories\UpdateCategoryRequest;
use App\Repositories\CategoryRepository;
use App\Http\Controllers\Controller;
use App\Services\ImageUpload;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{
    public $viewData = [];
    protected $repo;
    /**
     * @var ImageUpload
     */
    private $imageUpload;

    /**
     * CategoriesController constructor.
     * @param CategoryRepository $repo
     * @param ImageUpload $imageUpload
     */
    public function __construct(CategoryRepository $repo, ImageUpload $imageUpload)
    {
        $this->repo = $repo;
        $this->imageUpload = $imageUpload;
    }

    public function index()
    {

        $this->viewData['categories'] = $this->repo->all();

        return view('admin.categories.list', $this->viewData);
    }

    public function edit($id)
    {
        $this->viewData['item'] = $this->repo->findOrFail($id);
        if (!$this->viewData['item']) abort(404);
        $this->viewData['categories'] = $this->repo->getMain();

        return view('admin.categories.item', $this->viewData);
    }

    public function create()
    {
        $this->viewData['item'] = $this->repo->getModel();
        $this->viewData['categories'] = $this->repo->all();

        return view('admin.categories.item', $this->viewData);
    }

    public function store(StoreCategoryRequest $request)
    {
        //todo add base image width for categories image
        $category = $this->repo->create($request->except(['_token', 'image']));
        if ($category) {
            if ($request->file('image')) {
                $this->imageUpload->baseFolder = 'categories';
                $imagePath = $this->imageUpload->save($request->file('image'), 800);
                if ($imagePath) {
                    $this->repo->update($category->id, ['image' => $imagePath]);
                }
            } else if ($request->get('image')) {
                $this->imageUpload->baseFolder = 'categories';
                $imagePath = $this->imageUpload->save($request->get('image'), 800);
                if ($imagePath) {
                    $this->repo->update($category->id, ['image' => $imagePath]);
                }
            }

            return redirect()->route('admin.categories.index')->with('success', __('flash.created'));
        } else {
            return back()->withInput()->with('error', __('flash.error'));
        }
    }

    public function update(UpdateCategoryRequest $request, $id)
    {
        $data = $request->except(['_token', 'image']);
        $category = $this->repo->find($id);

        if ($request->file('image')) {
            $this->imageUpload->baseFolder = 'categories';
            $imagePath = $this->imageUpload->save($request->file('image'), 800, null, 'update', $category ? $category->image : '');
            if ($imagePath) {
                $this->repo->update($category->id, ['image' => $imagePath]);
            }
        } else if ($request->get('image')) {
            $this->imageUpload->baseFolder = 'categories';
            $imagePath = $this->imageUpload->save($request->get('image'), 800, null, 'update', $category ? $category->image : '');
            if ($imagePath) {
                $this->repo->update($category->id, ['image' => $imagePath]);
            }
        }

        $category = $this->repo->update($id, $data);
        if ($category) {
            if ($request->ajax()) {
                return response(['status' => 'success', 'message' => __('flash.updated')]);
            }

            return redirect()->route('admin.categories.index')->with('success', __('flash.updated'));
        } else {
            if ($request->ajax()) {
                return response(['status' => 'danger', 'message' => __('flash.error')]);
            }

            return back()->withInput($request->all())->with('error', __('flash.error'));
        }
    }

    public function destroy(DeleteCategoryRequest $request, $id)
    {
        $category = $this->repo->find($id);
        if ($category) {
            $this->imageUpload->deleteImage($category->image);
        }
        if ($category->delete()) {
            return redirect()->route('admin.categories.index')->with('success', __('flash.deleted'));
        } else {
            return back()->withInput()->with('error', __('flash.error'));
        }
    }

    public function deleteImg(Request $request)
    {
        $category = $this->repo->find($request->get('key', 0));
        $category->update(['image' => null]);
        if ($category) {
            $deleted = $this->imageUpload->deleteImage($category->image);
            if ($deleted) {
                return response(['status' => 'success', 'message' => __('flash.deleted')]);
            } else {
                return response(['status' => 'danger', 'message' => __('flash.error')]);
            }
        } else {
            return response(['status' => 'error', 'message' => __('flash.not_found')], 404);
        }

    }

    public function active(UpdateCategoryRequest $request)
    {
        $response = [];

        if ($this->repo->changeStatus($request->except(['_token']))) {
            $response['status'] = 'success';
            $response['message'] = __('flash.updated');
        } else {
            $response['status'] = 'danger';
            $response['message'] = __('flash.error');
        }

        return response()->json($response);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Repositories\CategoryRepository;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * @var CategoryRepository
     */
    private $model;

    public function __construct(CategoryRepository $model)
    {
        $this->model = $model;
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
//        if ($request->get('is_for_sale')) {
            $categories = $this->model->active()->forSale()->get();
//        } else {
//            $categories = $this->model->active()->get();
//        }
        $response = [
          'status' => 'ok',
          'data' => $categories,
        ];

        return response()->json($response);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        //
    }
}

resources/views/admin/categories/list.blade.php
@extends('admin.layouts.common')

@section('title')Список категорий @endsection
@push('scripts')
    <script type="text/javascript" src="{{ asset('back/assets/js/plugins/forms/styling/switch.min.js') }}"></script>
    <script>
        $(function() {
            $('.switch').bootstrapSwitch().on('switchChange.bootstrapSwitch', function(event, state) {
                var obj = $(this),
                        data = state ? 1 : 0;
                $.ajax({
                    url: $(this).data('url'),
                    method: 'put',
                    data: {
                        active: data
                    },
                    dataType: 'json',
                    success: function(response) {
                        new PNotify({
                            text: response.message,
                            type: response.status
                        });
                    }
                });
            });
        });
    </script>
@endpush
@section('content')

    @push('active_breadcrumb')
        Список категорий
    @endpush
    <div class="row">
        <div class="col-xs-12">
            <div class="panel panel-flat">
                <div class="panel-heading">
                    <h6 class="panel-title">Categories list</h6>
                    <a href="{{ route('admin.categories.create') }}" class="btn btn-success pull-right"><i class="fa fa-plus"></i> Create</a>
                </div>
                <div class="panel-body">Список категорий</div>
                <div class="table-responsive">
                    <table class="table text-nowrap">
                        <thead>
                        <tr class="active">
                            <th class="text-center">#</th>
                            <th>Name</th>
                            <th>Image</th>
                            {{--<th>On main?</th>--}}
                            <th class="text-center">Status</th>
                            <th class="text-center">Created At</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($categories as $category)
                            <tr>
                                <td class="text-center">
                                    <h6 class="no-margin"><small class="display-block text-size-small no-margin">{{$category->id}}</small></h6>
                                </td>
                                <td>
                                    <a href="{{ route('admin.categories.edit', ['id' => $category->id]) }}" class="display-inline-block text-default text-semibold letter-icon-title">{{$category->title}}</a>
                                </td>
                                <td>
                                    @if ($category->image)
                                        <img src="{{ asset($category->image) }}" width="120">
                                    @endif
                                </td>
                                {{--<td>--}}
                                    {{--@if ($category->show_on_main)--}}
                                        {{--<span class="label label-warning">Yes</span>--}}
                                    {{--@else--}}
                                        {{--<span class="label label-primary">No</span>--}}
                                    {{--@endif--}}
                                {{--</td>--}}
                                <td class="text-center">
                                    <div class="checkbox checkbox-switch checkbox-switch-xs">
                                        <label>
                                            <input type="checkbox" class="switch" data-id="{{$category->id}}" data-on-text="On" data-off-text="Off" data-on-color="success" data-off-color="default" data-url="{{ route('admin.categories.update', ['id' => $category->id]) }}" data-size="small" @if($category->active)checked="checked"@endif>
                                        </label>
                                    </div>
                                </td>
                                <td class="text-center">
                                    {{$category->created_at}}
                                </td>
                                <td class="text-center">
                                    <div class="btn-group">
                                        {{--<a href="{{ route('admin.categories.show', ['category' => $category->slug]) }}" target="_blank" class="btn btn-primary btn-xs"><i class="fa fa-eye"></i></a>--}}
                                        <a href="{{ route('admin.categories.edit', ['id' => $category->id]) }}" class="btn btn-default btn-xs"><i class="fa fa-pencil"></i> Edit</a>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

@endsection