routes/web.php
<?php

/**
 * @var \Illuminate\Routing\Router $router
 */
$router->auth();
$router->get('auth/{provider}/sign', 'Auth\SocialSignController@redirectToProvider')->name('auth.social_sign');
$router->get('auth/{provider}/callback', 'Auth\SocialSignController@handleProviderCallback')->name('auth.social_sign_callback');

$router->get('/', 'HomeController@index')->name('index');
$router->get('home', 'HomeController@index')->name('home');
$router->get('countries/regions', 'RegionController@getRegionsByCountry')->name('countries.get_regions');
$router->get('regions/cities', 'CityController@getRegionsByCountry')->name('regions.get_cities');
$router->get('cities', 'CityController@index')->name('cities.index');
$router->get('cities/{id}', 'CityController@show')->name('city.show');
$router->get('breeds', 'BreedController@index')->name('breeds.index');

$router->get('pets', 'PostController@index')->name('posts.index');
$router->get('pets/{slug}', 'PostController@show')->name('posts.show');


//$router->get('shop', 'PostController@productsIndex')->name('posts.index');
//$router->get('shop/{category}/{slug}', 'PostController@showProduct')->name('posts.show');

$router->post('pets/send-message', 'PostController@submitMessage')->name('posts.send_message');

$router->get('organizations', 'OrganizationController@index')->name('organizations.index');
$router->get('organizations/{slug}', 'OrganizationController@show')->name('organizations.show');

Route::get('sitemap', function () {
    return redirect()->route('sitemap_xml', 302);
});
Route::get('sitemap.xml', 'HomeController@sitemap')->name('sitemap_xml');


$router->group(['middleware' => 'auth', 'prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Profile'], function () use ($router) {
    $router->get('/', 'IndexController@index')->name('index');
    $router->put('update', 'IndexController@update')->name('update');
    $router->get('favourites', 'FavouritesController@index')->name('favourites.index');
    $router->post('posts/add-to-favourites', 'PostController@addToFavourites')->name('posts.add_to_favourites');
    $router->delete('posts/remove-from-favourites', 'PostController@removeFromFavourites')->name('posts.remove_from_favourites');
    $router->post('posts/delete-image', 'PostController@deleteImage')->name('posts.delete_image');
    $router->post('posts/photos/mark-as-main', 'PostController@markPhotoAsMain')->name('posts.photos.mark_as_main');
    $router->put('posts/change-home-status/{id}', 'PostController@changeHomeStatus')->name('posts.change_home_status');
    $router->resource('posts', 'PostController');

    $router->post('organizations/delete-image', 'OrganizationController@deleteImage')->name('organizations.delete_image');
    $router->resource('organizations', 'OrganizationController');
});
$router->group(['middleware' => 'can:admin', 'prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function () use ($router) {
    $router->get('/', 'IndexController@index')->name('index');
    $router->get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

    $router->get('grabber', 'IndexController@grabber')->name('grabber.index');
    $router->post('grabber', 'IndexController@grabberRun')->name('grabber.run');

    $router->get('robots', 'IndexController@robots')->name('robots.index');
    $router->post('robots', 'IndexController@storeRobots')->name('robots.store');

    $router->post('categories/delete-img', 'CategoriesController@deleteImg')->name('categories.delete_img');
    $router->resource('categories', 'CategoriesController');
    $router->resource('users', 'UsersController');
    $router->resource('settings', 'SettingsController');
    $router->resource('pages', 'PageController');
    $router->resource('posts', 'PostController');
    $router->resource('breeds', 'BreedController');
    $router->resource('breed-types', 'BreedTypeController');
    $router->resource('post-types', 'PostTypeController');
    $router->resource('colors', 'ColorController');
    $router->resource('countries', 'CountryController');
    $router->resource('regions', 'RegionController');
    $router->resource('cities', 'CityController');
    $router->resource('organizations', 'OrganizationController');
    $router->resource('organization-types', 'OrganizationTypeController');

});

$router->get('{slug}', 'HomeController@showStaticPage')->name('page.show');

resources/views/admin/includes/menu.blade.php
<ul class="navigation navigation-main navigation-accordion">
    <li class="navigation-header"><span>Пользователи</span></li>
    <li class="{{ Route::is('admin.user*') ? 'active' : '' }}">
        <a href="{{ route('admin.users.index') }}"><i class="icon-users2"></i> <span>Пользователи</span></a>
    </li>
    <li class="navigation-header"><span>Объявления</span></li>
    <li class="{{ Route::is('admin.posts*') ? 'active' : '' }}">
        <a href="{{ route('admin.posts.index') }}"><i class="icon-users2"></i> <span>Объявления</span></a>
    </li>
    <li class="{{ Route::is('admin.breed-types*') ? 'active' : '' }}">
        <a href="{{ route('admin.breed-types.index') }}"><i class="icon-bug2"></i> <span>Животные</span></a>
    </li>
    <li class="{{ Route::is('admin.breeds*') ? 'active' : '' }}">
        <a href="{{ route('admin.breeds.index') }}"><i class="icon-tux"></i> <span>Породы</span></a>
    </li>
    <li class="{{ Route::is('admin.colors*') ? 'active' : '' }}">
        <a href="{{ route('admin.colors.index') }}"><i class="icon-color-sampler"></i> <span>Расцветки</span></a>
    </li>
    <li class="{{ Route::is('admin.post-types*') ? 'active' : '' }}">
        <a href="{{ route('admin.post-types.index') }}"><i class="icon-database2"></i> <span>Типы объяв</span></a>
    </li>

    <li class="{{ Route::is('admin.categories*') ? 'active' : '' }}">
        <a href="{{ route('admin.categories.index') }}"><i class="icon-magazine"></i> <span>Категории продажи</span></a>
    </li>

    <li class="navigation-header"><span>Организации</span></li>
    <li class="{{ Route::is('admin.organization-types*') ? 'active' : '' }}">
        <a href="{{ route('admin.organization-types.index') }}"><i class="icon-home2"></i> <span>Типы организаций</span></a>
    </li>
    <li class="{{ Route::is('admin.organizations*') ? 'active' : '' }}">
        <a href="{{ route('admin.organizations.index') }}"><i class="icon-home"></i> <span>Организации</span></a>
    </li>
    {{--<li class="navigation-header"><span>Categories</span></li>--}}
    {{--<li class="{{ Route::is('admin.categories*') ? 'active' : '' }}">--}}
        {{--<a href="{{ route('admin.categories.index') }}"><i class="icon-color-sampler"></i> <span>Categories</span></a>--}}
    {{--</li>--}}

    <li class="navigation-header"><span>Локация</span></li>
    <li class="{{ Route::is('admin.countries*') ? 'active' : '' }}">
        <a href="{{ route('admin.countries.index') }}"><i class="icon-map"></i> <span>Страны</span></a>
    </li>
    <li class="{{ Route::is('admin.regions*') ? 'active' : '' }}">
        <a href="{{ route('admin.regions.index') }}"><i class="icon-map"></i> <span>Регионы</span></a>
    </li>
    <li class="{{ Route::is('admin.cities*') ? 'active' : '' }}">
        <a href="{{ route('admin.cities.index') }}"><i class="icon-map"></i> <span>Города</span></a>
    </li>

    <li class="navigation-header"><span>Статические страницы</span></li>
    <li class="{{ Route::is('admin.pages*') ? 'active' : '' }}">
        <a href="{{ route('admin.pages.index') }}"><i class="icon-newspaper"></i> <span>Статические страницы</span></a>
    </li>

    <li class="navigation-header"><span>Система</span></li>
    <li class="{{ Route::is('admin.robots*') ? 'active' : '' }}">
        <a href="{{ route('admin.robots.index') }}"><i class="icon-file-eye2"></i> <span>Robots.txt</span></a>
    </li>
    <li class="{{ Route::is('admin.settings*') ? 'active' : '' }}">
        <a href="{{ route('admin.settings.index') }}"><i class="icon-cogs"></i> <span>Настройки</span></a>
    </li>
    <li class="{{ Route::is('admin.grabber*') ? 'active' : '' }}">
        <a href="{{ route('admin.grabber.index') }}"><i class="icon-grab"></i> <span>Парсер постов</span></a>
    </li>
</ul>